name: zoli
favicon: null
layout_spectrum: 0.4507582827936858
typography_spectrum: 0.10252148262225091
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.35308792418800294
  lightness: 0.9365659598261118
  saturation: 0.1649422503542155
  rhythmicContrast: 0.9861593600362539
purpose: []
